version: "3.9"

services:
  proxy:
    image: pharmifyregistry.azurecr.io/proxy:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    
  frontend:
    image: pharmifyregistry.azurecr.io/frontend:latest
    restart: unless-stopped
    environment:
      - PORT=80

  api:
    image: pharmifyregistry.azurecr.io/api:latest
    restart: unless-stopped
    environment:
      - PORT=80

  database:
    image: pharmifyregistry.azurecr.io/database:latest
    restart: unless-stopped
    environment:
      - PORT=3306